### ISSUE TITLE
themes/catppuccin.nix errouneously references "waylbar" in two locations

### ISSUE THREAD

**Issue by maxbol** [Cu3PO42/gleaming-glacier#5]
First location is here: https://github.com/Cu3PO42/gleaming-glacier/blob/next/themes/catppuccin.nix#L10
* The function actually being passed in is called `waybarOverrides`, not `waylbarOverrides`

Second location is here: https://github.com/Cu3PO42/gleaming-glacier/blob/next/themes/catppuccin.nix#L76
* Settings the `colorOverrides` of `waylbar` does nothing as this is not the name of an actual chroma integration

:)

OT: Chroma is great, I've ported gruvbox and soon rosepine to it and added a functioning tmux integration and a not so functioning nvchad integration!

**Comment by Cu3PO42** [comment]
Welp. Thank you so much for catching that one. It must have happened during some refactor. I knew something felt off...

I love to hear that Chroma is working great for you. At some point in the hopefully not-so-distant future, I may include your themes. Also, I'm currently in the (slow and arduous) process of writing documentation. I'd love to hear if there's any particular pitfalls you encountered that you'd like to see addressed.

**Comment by Cu3PO42** [comment]
I absolutely agree this doesn't belong in the dynachrome template. It's just there for historic reasons. This part of the config is derived from prasanthrangan/hyprdots and they have the border radius in the theme files. I meant to refactor it, and I just haven't yet.

I'd be happy to accept your contributions on this, though I would probably rather move this to the main Hyprland config than a new per-theme file. Although, there is an argument to be made to seperate color settings from other theme settings, such as gap and border size, etc. Feel free to open up a discussion on this.
